# Generated by Django 3.1.2 on 2020-12-20 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SierraWeb', '0002_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquetes',
            fields=[
                ('id_paquete', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('lugar', models.TextField()),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserPaquete',
            fields=[
                ('id_userpaquete', models.AutoField(primary_key=True, serialize=False)),
                ('id_paquete', models.ForeignKey(db_column='id_paquete', on_delete=django.db.models.deletion.DO_NOTHING, to='SierraWeb.paquetes')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='SierraWeb.usuarios')),
            ],
        ),
    ]
