# Generated by Django 3.1.2 on 2021-01-01 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SierraWeb', '0003_paquetes_userpaquete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaquete',
            name='id_paquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SierraWeb.paquetes'),
        ),
        migrations.AlterField(
            model_name='userpaquete',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SierraWeb.usuarios'),
        ),
    ]
