# Generated by Django 3.1.2 on 2021-01-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SierraWeb', '0004_auto_20210101_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaquete',
            name='nombre_paquete',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
