# Generated by Django 3.1.2 on 2021-01-10 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SierraWeb', '0009_delete_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=20)),
                ('apellido_cliente', models.CharField(max_length=40)),
                ('correo_cliente', models.EmailField(max_length=100)),
                ('status', models.CharField(max_length=15)),
                ('codigo_estado', models.CharField(max_length=100)),
                ('paquete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SierraWeb.paquetes')),
            ],
        ),
    ]
