# Generated by Django 3.1.2 on 2021-01-17 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SierraWeb', '0012_auto_20210109_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=30)),
                ('apellido_usuario', models.CharField(max_length=40)),
                ('nombre_paypal', models.CharField(max_length=30)),
                ('apellido_paypal', models.CharField(max_length=40)),
                ('correo_cliente', models.EmailField(max_length=100)),
                ('n_personas', models.CharField(max_length=10)),
                ('fecha_paquete', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=15)),
                ('codigo_estado', models.CharField(max_length=100)),
                ('total_de_compra', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userpaquete',
            name='id_paquete',
        ),
        migrations.RemoveField(
            model_name='userpaquete',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='paquetes',
            name='fecha',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='UserPaquete',
        ),
        migrations.AddField(
            model_name='compras',
            name='paquete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SierraWeb.paquetes'),
        ),
    ]
