# Generated by Django 3.1.2 on 2021-01-20 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SierraWeb', '0013_auto_20210116_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquetes',
            name='fecha',
        ),
    ]
